---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  annotations:
    kubernetes.io/service-account.name: "jenkins-token"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-schedule-agents-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "persistentvolumeclaims"]
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
- apiGroups: ["", "apps"]
  resources: ["secrets", "deployments", "events"]
  verbs: ["create","get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-schedule-agents-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-schedule-agents-role
subjects:
- kind: ServiceAccount
  name: jenkins-service-account
