namespace: member
bases:
  - ../base

resources:
  - secret.yaml
  - ingress.yaml

commonLabels:
  layer: backend
  service: member

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: member-configmap
    envs:
      - config.env

patches:
  - patch : |-
      - op: replace
        path: /metadata/name
        value: "member"
    target:
      kind: Namespace
      name: namespace

  - patch : |-
      - op: replace
        path: /metadata/name
        value: "member-service"
    target:
      kind: Deployment
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "member"
    target:
      kind: Service
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "member"
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/service-account.name: "member-token"
    target:
      kind: ServiceAccount
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "member-role"
    target:
      kind: ClusterRole
      name: app

  - patch: |-
      - op: replace
        path: /metadata/name
        value: "member-rolebinding"
    target:
      kind: ClusterRoleBinding
      name: app